### ISSUE TITLE
question - 3D Keypoint model

### ISSUE THREAD

**Issue by JotaBravo** [tpark94/speedplusbaseline#1]
Hi,

Thanks for sharing this nice implementation. 

I've noticed that in the configuration file you mention the existence of a 3D keypoint model, but unfortunately it does not appear in the repository.

```
# ------------------------------------------------------------------------------------------
# Model config.
parser.add_argument('--model_name',      type=str,   default='krn')
parser.add_argument('--input_shape',     nargs='+',  type=int, default=(224, 224))
parser.add_argument('--num_keypoints',   type=int,   default=11)   # KRN-specific
parser.add_argument('--num_classes',     type=int,   default=5000) # SPN-specific
parser.add_argument('--num_neighbors',   type=int,   default=5)    # SPN-specific
parser.add_argument('--keypts_3d_model', type=str,   default='src/utils/tangoPoints.mat')
```

Are you planning to release this 3D model?

Thanks

**Comment by tpark94** [comment]
Hello,

The 3D keypoint models won't be released, at least as long as the competition is ongoing. However, you can check the original paper for how the keypoints were recovered from SPEED synthetic images:

Park T. H., Sharma S., D'Amico S. _Towards Robust Learning-Based Pose Estimation of Noncooperative Spacecraft_. 2019 AAS/AIAA Astrodynamics Specialist Conference, Portland, Maine, August 11 - 15 (2019).

We'll post the details not presented in the paper (e.g., order of keypoints) when we update the repository in the future.

Best regards,
Jeff Park

**Comment by Ashayan97** [comment]
> 

Hi, 
Since the competition is closed now, is there any possibility of sharing the 3D keypoints file?

Best regards,
Amirshayan Nasirimajd
