### ISSUE TITLE
camera.json

### ISSUE THREAD

**Issue by Rahul-Shedge** [tpark94/speedplusbaseline#2]
Can u share your camera.json file? How u computed those, i am very new to this.

**Comment by tpark94** [comment]
Hello, 

The `camera.json` file is part of the SPEED+ dataset and can be obtained from this [link](https://purl.stanford.edu/wv398fc4383).

Jeff

**Comment by Rahul-Shedge** [comment]
Thanks

Will this code work for SPEED as well?

**Comment by tpark94** [comment]
It will work, but I haven't tried it with SPEED so some small modifications may or may not be required.

Since SPEED doesn't come with a `camera.json` file, you'll have to create one based on the camera parameters listed in the paper for SPN. Simply set the distortion coefficients to a zero vector.

**Comment by Rahul-Shedge** [comment]
Thanks for the information.
