### ISSUE TITLE
bounding box labels?

### ISSUE THREAD

**Issue by jwberck** [tpark94/speedplusbaseline#3]
Since the competition is supposed to be over by now, can you upload the bounding boxes and such?

Currently Unavailable Features
"CSV files containing bounding box and keypoint labels (KRN) or spacecraft attitude classes (SPN) for all domains of SPEED+"

**Comment by tpark94** [comment]
I'm sorry for the late response.

The organizing team is still discussing when to release the labels for the lightbox and sunlamp domains. In the meantime, there is a post-mortem competition going on at the same [website](https://kelvins.esa.int/pose-estimation-2021/), where you can still submit your solutions and have them evaluated.

Unfortunately, this means I cannot upload the CSV files and other labels until we decide to stop the post-mortem competition and upload the test labels to the official dataset repository. I'll make sure to upload them as soon as it happens, however.

Best,
Jeff

**Comment by 666666jh** [comment]
Hi,I'm very instrested in Object Detection Network in this paper:TOWARDS ROBUST LEARNING-BASED POSE ESTIMATION OF
NONCOOPERATIVE SPACECRAFT.Could you provide code about this network?Thank you very much!
