### ISSUE TITLE
How to create test.csv in synthetic domain?

### ISSUE THREAD

**Issue by 666666jh** [tpark94/speedplusbaseline#6]
Hi,thank you for your sharing excellent work!  But I don't konw how to create test.csv in synthetic domain because there is not test.json in synthetic folder.In the repository,test.csv of synthetic domain is needed for training.Looking forward to your answers!

**Comment by tpark94** [comment]
Hello, 

Please note that there is no test.csv in synthetic domain. Since the purpose of SPEED+ is to evaluate robustness across domain gap (i.e., out-of-distribution generalization, sim2real), we do not provide test set for in-distribution domain (i.e., synthetic).

**Comment by 666666jh** [comment]
![image](https://user-images.githubusercontent.com/76036785/231362931-f7ef9253-e82f-4d17-bd03-0a7b44c8beaa.png)

Firstly,thank you for your timely response! 
I understand what you mean，but I don't konw  why test.csv is used in pocess of training synthetic dataset,as this screenshot above illustrates.

**Comment by tpark94** [comment]
Yes, that's a mistake on my part, sorry for that. Please also note that those code snippets are only provided as a template to run the script.

**Comment by 666666jh** [comment]
Ok!And then I'm very instrested in Object Detection Network in this paper:TOWARDS ROBUST LEARNING-BASED POSE ESTIMATION OF
NONCOOPERATIVE SPACECRAFT,so I want to do further research.Could you provide code about this network?Thank you very much!

**Comment by 666666jh** [comment]
Ok!And then I'm very instrested in Object Detection Network in this paper:TOWARDS ROBUST LEARNING-BASED POSE ESTIMATION OF NONCOOPERATIVE SPACECRAFT,so I want to do further research.Could you provide code about this network?Thank you very much!

**Comment by tpark94** [comment]
We do not plan to release ODN codes at the moment for a number of reasons
1. It closely follows YOLOv3 with minor changes, so any other public repos with implementations of YOLOv3 can be used
2. The effect of object detection performance on KRN performance is minimal as long as KRN is trained to incorporate misaligned RoI
3. This means any publicly available object detection CNN can be used in place of the one specific ODN in the paper.
